#!/bin/sh
#
# double borders

_() { bspc config "$@"; }

# get values from bspwm config
outer='0x100D0C'
inner1='0x333B33'
inner2='0x100D0C'

draw() {
    case $1 in
        normal)  i=$inner2; o=$outer;;
        focused) i=$inner1; o=$outer
    esac

    shift

    chwb2 -I "$i" -O "$o" -i "4" -o "8" $@ 2> /dev/null
}

# initial draw, and then subscribe to events
{ echo; bspc subscribe node_geometry node_focus; } |
    while read -r _; do
        draw normal  "$(targets  normal)"
        draw focused "$(targets focused)"
    done
