#!/usr/bin/env sh
#                           ██            ████
#                          ░░            ░██░
#   ██████  ██   ██  ██████ ██ ███████  ██████  ██████
#  ██░░░░  ░░██ ██  ██░░░░ ░██░░██░░░██░░░██░  ██░░░░██
# ░░█████   ░░███  ░░█████ ░██ ░██  ░██  ░██  ░██   ░██
#  ░░░░░██   ░██    ░░░░░██░██ ░██  ░██  ░██  ░██   ░██
#  ██████    ██     ██████ ░██ ███  ░██  ░██  ░░██████
# ░░░░░░   ██      ░░░░░░  ░░ ░░░   ░░   ░░    ░░░░░░
#        ░░
#
#█▓▒░ vars
#FULL=▓
#EMPTY=░
FULL=━
#EMPTY=━
#EMPTY=─
#FULL=┅
EMPTY=┄

name=$USER
host=$(hostname)
battery="/sys/class/power_supply/BAT?"
distro="Arch Linux"
kernel=$(uname -r)
pkgs=$(pacman -Qqs | wc -l)
wm=$(awk '/exec/ { printf $2 }' ~/.xinitrc)


#xdef=$(grep "themes" ~/.config/xrdb/Xdefaults | cut -d '"' -f2)
#xdef="${xdef#*/}"
#colors="$xdef"

#█▓▒░ progress bar
draw() {
	perc=$1
	size=$2
	inc=$((perc * size / 100))
	color="${3-36}"
	v=0
	while [ "$v" -le 10 ]; do
		if [ $v -le $inc ]; then
			out="${out}\033[1;${color}m${FULL}"
		else
			out="${out}\033[0;${color}m${EMPTY}"
		fi
		v=$((v + 1))
	done
	printf "%b\n" "$out"
}


#█▓▒░ greets
printf " \033[0m  Hello \033[36m$name\033[0m, I'm \033[34m$host\n\n\033[0m"

#█▓▒░ environment
printf " \033[1;33m      distro \033[0m$distro\n"
printf " \033[1;33m      kernel \033[0m$kernel\n"
printf " \033[1;33m    packages \033[0m$pkgs\n"
printf " \033[1;33m          wm \033[0m$wm\n"
