static const char *font = "JetBrains Mono:size=9";
static const char *background = "#141417";
static const char *foreground = "#828595";
static const char *selbackground = "#82AAFF";
static const char *selforeground = "#141417";
static const char *separator = "#CDC7C2";
static const char *border = "#5F655A";
static int width = 175;
static int itemborder = 4;
static int menuborder = 1;
static int separatorsize = 1;
