# Don't print a new line at the start of the prompt
add_newline = true

# Replace the "❯" symbol in the prompt with "➜"
[character]      # The name of the module we are configuring is "character"
symbol = "↳"     # The "symbol" segment is being set to "➜"

# Disable the package module, hiding it from the prompt completely
[package]
disabled = false

# Put everything in 1 line,don't separate time and command into the 2nd line
[line_break]
disabled = false

[time]
disabled = false
format = " ❯ %T "
utc_time_offset = "local"

[username]
disabled = false
show_always = true

[hostname]
ssh_only = false
prefix = ""
suffix = " ✘ ♰ ✘"
disabled = false

[git_branch]
symbol = " "
truncation_length = 15

[git_commit]
commit_hash_length = 10

[cmd_duration]
min_time = 100
prefix = "took "
